### ISSUE TITLE
Choose a feature for implementation

### ISSUE THREAD

**Issue by steinkohl** [steinkohl/microservices-demo#1]
## User story
1. As a Student 
2. I need to choose a Feature which will be implemented
3. So that I get Points for the Assignment

## Acceptance criteria
* Has to be a new micro service
* Should be little effort

## Definition of done
* All involved Students are in consensus

**Comment by steinkohl** [comment]
Suppose to implement a "Banner / Quote of the Day Service" or "Coupon service"

**Comment by steinkohl** [comment]
I think the "Quote of the Day" service would be the easiest approach, for this we only have to generate a quote on daily basis and display it, for example in the header of the frontend

**Comment by anastasiah00** [comment]
I think this is a good idea. Let's do that.

**Comment by sflorinho** [comment]
Yes, good idea. Coupon service might be more interesting but could be too extensive.
